---
title: "References"
---

Alleyn, P., and Phillips, K., (2011). Exploring Academic Dishonesty among University Students in Barbados: An Extension to the Theory of Planned Behaviour. Journal of Academic Ethics, Vol 9. 323.

Baumeister, R.,  Bratslavsky, E., Finkenauer, C., D. Vohs, K.(2001). Bad Is Stronger Than Good. Review Of General Psychology,Vol. 5. No. 4. 323-370

Bernedo, M., Ferraro, P. J., & Price, M. (2014). The persistent impacts of norm-based messaging and their implications for water conservation. Journal of Consumer Policy, 37(3), 437-452.

Beshears, J., Choi, J. J., Laibson, D., Madrian, B. C., & Milkman, K. L. (2015). The effect of providing peer information on retirement savings decisions. The Journal of finance, 70(3), 1161-1201.

Bicchieri, C. (2006). The Grammar of Society: The Nature and Dynamics of Social Norms. New York: Cambridge University Press. 

Bicchieri, C. (2016). Norms in the wild: How to diagnose, measure, and change social norms. Oxford University Press.

Bicchieri, C., Dimant, E. (2018). It's Not A Lie If You Believe It: Lying and Belief Distortion Under Norm-Uncertainty, a. University of Pennsylvania, b.Wharton School of Business, c. Behavioral Ethics Lab, d.CeDEx

Bicchieri, C., Dimant, E., Xiao, E (2017). Deviant or Wrong? The Effects of Norm Information on the Efficacy of Punishment, Centre for Decision Research and Experimental Economics, University of Nottingham

Bicchieri, C., Xiao, E (2008). Do the Right Thing: But Only if Others Do So. Journal of Behavioral Decision Making, J. Behav. Dec. Making, 22: 191–208

Bizer, G. Y., Larsen, J. T., & Petty, R. E. (2011). Exploring the valence‐framing effect: Negative framing enhances attitude strength. Political psychology, 32(1), 59-80.
Brandon, A., Ferraro, P. J., List, J. A., Metcalfe, R. D., Price, M. K., & Rundhammer, F. (2017).   Do the effects of social nudges persist? Theory and evidence from 38 natural field experiments (No. w23277). National Bureau of Economic Research.

Cialdini, R. B., Demaine, L. J., Sagarin, B. J., Barrett, D. W., Rhoads, K., & Winter, P. L. (2006). Managing social norms for persuasive impact. Social influence, 1(1), 3-15.
Cialdini, R., Kallgren, C., Reno, R. (1991). A focus theory of normative conduct: A theoretical refinement and reevaluation of the role of norms in human behavior. In Advances in experimental social psychology (Vol. 24, pp. 201-234). Academic Press.

Cialdini, R., Kallgren, C., Reno, R. (1993). The Transsituational Influence of Social Norms. Journal of Personality and Social Psychology, Vol.64, No. 1,104-112

Charness,G. Gneezy, U. (2012). Strong Evidence for Gender Differences in Risk Taking, Journal of Economic Behavior & Organization Volume 83, Issue 1, Pages 50-58

Dreber, A., & Johannesson, M. (2008). Gender differences in deception. Economics Letters, 99(1), 197-199.

Fagley, N.S, Coleman, J., Simon, A. (2009) Effects of framing, perspective taking, and perspective (affective focus) on choice.  Personality and Individual Differences, GSAPP, Rutgers University, Western New Mexico University,Seton Hall University.

Kahneman, D, (2003). A Perspective on Judgment and Choice Mapping Bounded Rationality, American Psychologist 697, American Psychological Association, Inc.  Vol. 58, No. 9, 697–720

Kajackaite, A., & Gneezy, U. (2017). Incentives and cheating. Games and Economic Behavior, 102, 433-444.

Levin, I. P., & Gaeth, G. J. (1988). Framing of attribute information before and after consuming the product. Journal of Consumer Research, 15, 374–378. 

Levin, I. P., Schneider, S. L., & Gaeth, G. J. (1998). All frames are not created equal: A typology and critical analysis of framing effects. Organizational behavior and human decision processes, 76(2), 149-188.

Meyerowitz, B. E., & Chaiken, S. (1987). The effect of message framing on breast self-examination attitudes, intentions, and behavior. Journal of Personality and Social Psychology, 52, 500–510.
 
Moss, N., Hamilton, K., White, K., Hansen, J., (2014). The changing motivations of students use of lecture podcasts across a semester: an extended theory of planned behavior approach. Innovations in Education and Teaching International. 52 (6): 1-11. 

Park, E. S. (2000). Warm-glow versus cold-prickle: a further experimental study of framing effects on free-riding. Journal of Economic Behavior & Organization, 43(4), 405-421.
Richter, I., Thøgersen, J., & Klöckner, C. (2018). A social norms intervention going wrong: Boomerang effects from descriptive norms information. Sustainability, 10(8), 2848.

Rolls, E., (2005) Emotion explained. Oxford University Press, London.

Rolls, E. T. (2014). Emotion and decision-making explained: a précis. cortex, 59(185), 93.

Rucker, D. D., Petty, R. E., & Briñol, P. (2008). What's in a frame anyway?: A meta‐cognitive analysis of the impact of one versus two sided message framing on attitude certainty. Journal of Consumer Psychology, 18(2), 137-149.

Smith, S. M., & Petty, R. E. (1996). Message framing and persuasion: A message processing analysis. Personality and Social Psychology Bulletin, 22, 257–268.

Schultz, P. W., Nolan, J. M., Cialdini, R. B., Goldstein, N. J., & Griskevicius, V. (2007). The constructive, destructive, and reconstructive power of social norms. Psychological science, 18(5), 429-434.

Ter Meer, J. (2014). The indirect effect of monetary incentives on deception (No. 05-04). Cologne Graduate School in Management, Economics and Social Sciences.


Tom, S., Foc, C., Trepel, C., Poldtrack, R., (2007). The neural basis of loss aversion in decision-making under risk. Science. 515-518. 

Vargha, A., & Delaney, H. D. (1998). The Kruskal-Wallis test and stochastic homogeneity. Journal of Educational and Behavioral Statistics, 23(2), 170-192.

Wild, C., & Seber, G. (2011). The Wilcoxon rank-sum test.





